version: '3.9'
services:  
  account_management_service:
    build:
      context: ./account_management_service
    container_name: accounts-ct
    ports:
      - "5000:5000"
  payment_handling_service:
    build:
      context: ./payment_handling_service
    container_name: payment-ct
    ports:
      - "5001:5000"
  shippingservice:
    build:
      context: ./shippingservice
    container_name: shipping-ct
    ports:
      - "5002:5000"
  app_interaction_service:
    build:
      context: ./app_interaction_service
    container_name: app-interaction-ct
    ports:
      - "5003:5000"
