version: '3.9'
services:  
  account_management_service:
    build:
      context: ./account_management_service
    container_name: accounts_ct
    ports:
      - "5000:5000"
  payment_handling_service:
    build:
      context: ./payment_handling_service
    container_name: payment_ct
    ports:
      - "5001:5000"