version: '3.9'
services:  
  account_management_service:
    build:
      context: ./account_management_service
    container_name: accounts_ct
    ports:
      - "5000:5000"
  payment_handling_service:
    build:
      context: ./payment_handling_service
    container_name: payment_ct
    ports:
      - "5001:5000"
  shippingservice:
    build:
      context: ./shippingservice
    container_name: shipping_ct
    ports:
      - "5002:5000"
  appservice:
    build:
      context: ./app_interaction_service
    container_name: appinteraction_ct
    ports:
      - "5003:5000"
