apiVersion: v1
kind: Service
metadata:
  name: account-management-service
  namespace: myapps
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: account-management