apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-interaction
  name: app-interaction
  namespace: myapps
spec:
  replicas: 2 # Creating two replicas of the POD
  selector:
    matchLabels:
      app: app-interaction
  template:
    metadata:
      labels:
        app: app-interaction
    spec:
      containers:
      - image: gcr.io/ada-group2/app-interaction:0.0.1 # Docker image name, that we pushed to GCR - use your project id
        name: prediction-ui
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
        - name: DB_URL
          value: sqlite:///beers.db
