apiVersion: v1
kind: Service
metadata:
  name: payment-handling-service
  namespace: myapps
spec:
  type: LoadBalancer
  ports:
  - port: 5001
    targetPort: 5000
  selector:
    app: payment-handling