apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shipment
  name: shipment
  namespace: myapps
spec:
  replicas: 2 # Creating two replicas of the POD
  selector:
    matchLabels:
      app: shipment
  template:
    metadata:
      labels:
        app: shipment
    spec:
      containers:
      - image: gcr.io/ada-group2/shipment:0.0.1 # Docker image name, that we pushed to GCR - use your project id
        name: shipment
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
        - name: DB_URL
          value: sqlite:///shipping.db
        env:
        - name: AUTH_URL
          value: http://accounts-ct:5000/get_user
